### ISSUE TITLE
[tip] regex camelCase field name and Sentence case title

### ISSUE THREAD

**Issue by alejandrovrojas** [hdoro/sanity-snippets#4]
Most of the time I name fields the `name` and `title` values are the same, just formatted differently. Here's a snippet I use to take a camel case title, convert it to sentence case, and jump straight to the type. Thought I'd share this in case anyone would find it useful. 

![Screen Recording 2020-12-08 at 20 34 43-2](https://user-images.githubusercontent.com/6848068/101533621-5cd0d680-3996-11eb-8111-bff829e177bf.gif)

```
{
  "description": "Sanity field",
  "prefix": "field",
  "body": ["{", "\ttitle: '${1/(^.)|([A-Z](?=[a-z]))/${1:/upcase}${2:+ }${2:/downcase}/g}',", "\tname: '$1',", "\ttype: '$2',", "}"]
}
```

**Comment by hdoro** [comment]
This is brilliant, Alejandro! Sorry for the wait on this, still new to open-source and completely missed the notification.

Adding to the new version of the plugin, thanks!
