### ISSUE TITLE
Provide an option to select each schema types

### ISSUE THREAD

**Issue by surjithctly** [hdoro/sanity-snippets#7]
It would be great if we could select schema type for each field listed here: https://www.sanity.io/docs/schema-types

Currently, it provides only "sanityFld". For example, If I wanted to add Image schema inside a document, its not possible. 

Option 1: Add manual schema type for every schema type 
Option 2: Add VSCode Intellisense for each "type" in "sanityfld"

or, the cheapest option, provide an option to choose schama type for "type" same as you have given for SanitySchema Type object | document

Thanks a lot for this great extension.

**Comment by hdoro** [comment]
Hey Surjith 👋

This is a great idea! I think option 2 makes more sense as it's generally easier to reason about (less snippets to memorize)...

As I also wanted to make a couple of small changes, I went ahead and uploaded a new version with this feature. Thanks for the suggestion 🙌

**Comment by surjithctly** [comment]
Awesome. Works well. Thanks so much!
